name: Pipeline Python

on:
  push:
    branches:
      - main

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Executar script
        run: python calculadora.py

      - name: Executar teste
        run: python teste.py
